### ISSUE TITLE
Au::scale_by can overflow

### ISSUE THREAD

**Issue by Manishearth** [servo/app_units#25]
We just [round and cast](https://github.com/servo/app_units/blob/0a38715327a23bc824f2a24f96c59c38d9dfc0b2/src/app_unit.rs#L162). Casting can overflow.

Gecko seems to clamp at +/- 0x40000000 app units (`NSToCoordRoundWithClamp`). We should do the same.

See also: https://github.com/servo/app_units/issues/22

**Comment by Manishearth** [comment]
Should we use the same max value here? Or just INT_MAX?

cc @SimonSapin @emilio

**Comment by SimonSapin** [comment]
I don’t know. How was that max value picked?

**Comment by Manishearth** [comment]
```
10:18 < bz> Manishearth: 1<<30 means you can add two nscoords directly and check for overflow directly without ever triggering
            undefined behavior
```

Makes sense.

We should probably have this check in all operations.
